### ISSUE TITLE
Fails with Go 1.18 again

### ISSUE THREAD

**Issue by coder543** [uw-labs/lichen#15]
It appears to be failing on blank lines in the output of `go version -m`. This is the complete output:

```
2022/03/15 12:49:04 failed to evaluate licenses: unrecognised line: 	
```

**Comment by coder543** [comment]
the blank lines appear to be related to dependencies that have been replaced with a `replace` directive.

**Comment by nick-jones** [comment]
It looks like this might have been introduced in https://github.com/golang/go/commit/765c9116be44641854f580c19e3589d7b86a3d28 - I suspect it wasn't intentional. Either way, I'll make a change to get it to skip blank lines.
