### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by skitt** [uw-labs/lichen#19]
Hi,

Would it be possible to tag a new release? Installing `lichen` on a system with Go 1.18 now results in a binary which fails in certain circumstances (#15). It’s possible to build a binary from master of course but being able to install directly would be much more convenient.

Regards,

Stephen

**Comment by nick-jones** [comment]
I've pushed a new tag, `v0.1.6` (happy to tag again if we get some resolution to #20 too)
