### ISSUE TITLE
Fails with Go 1.18 dep lines instead of mod lines

### ISSUE THREAD

**Issue by skitt** [uw-labs/lichen#20]
At least in some circumstances, `go version -m` with Go 1.18 on a binary built with Go 1.18 outputs the current module as a `dep` line instead of the previous `mod` line, _i.e._

```
        dep     github.com/submariner-io/submariner     (devel) 
```

instead of

```
        mod     github.com/submariner-io/submariner     (devel) 
```

`lichen` then fails with

```
{
        "Path": "github.com/submariner-io/submariner",
        "Version": "(devel)",
        "Error": "github.com/submariner-io/submariner@(devel): invalid version: reading https://proxy.golang.org/github.com/submariner-io/submariner/@v/%28devel%29.info: 410 Gone\n\ts
erver response: not found: github.com/submariner-io/submariner@(devel): invalid version: unknown revision (devel)"
}
```

**Comment by nick-jones** [comment]
Interesting! Do you happen to know what those circumstances are? I've tried building submariner locally and at least for a basic compile I'm getting the expected results:

```
➜  submariner git:(devel) ✗ go version -m submariner | rg 'github.com/submariner-io/submariner'
	path	github.com/submariner-io/submariner
	mod	github.com/submariner-io/submariner	(devel)
```

**Comment by skitt** [comment]
It seems like building with `go build -o foo main.go` produces binaries like this. On `lichen` itself, I get

```
lichen: go1.17.6
	path	command-line-arguments
	mod	github.com/uw-labs/lichen	(devel)	
	dep	github.com/cpuguy83/go-md2man/v2	v2.0.1	h1:r/myEWzV9lfsM1tFLgDyu0atFtJ1fXn261LKYj/3DxU=
```

as expected with Go 1.17, but

```
lichen: go1.18.1
	path	command-line-arguments
	dep	github.com/cpuguy83/go-md2man/v2	v2.0.1	h1:r/myEWzV9lfsM1tFLgDyu0atFtJ1fXn261LKYj/3DxU=
[…]
2pxjjDFgDxSPtO8WSdbndj17Wu2y8vOT86wE/tjr+I=
	dep	github.com/uw-labs/lichen	(devel)	
```

with Go 1.18.

**Comment by nick-jones** [comment]
> It seems like building with `go build -o foo main.go` produces binaries like this. On `lichen` itself, I get
> 
> ```
> lichen: go1.17.6
> 	path	command-line-arguments
> 	mod	github.com/uw-labs/lichen	(devel)	
> 	dep	github.com/cpuguy83/go-md2man/v2	v2.0.1	h1:r/myEWzV9lfsM1tFLgDyu0atFtJ1fXn261LKYj/3DxU=
> ```
> 
> as expected with Go 1.17, but
> 
> ```
> lichen: go1.18.1
> 	path	command-line-arguments
> 	dep	github.com/cpuguy83/go-md2man/v2	v2.0.1	h1:r/myEWzV9lfsM1tFLgDyu0atFtJ1fXn261LKYj/3DxU=
> […]
> 2pxjjDFgDxSPtO8WSdbndj17Wu2y8vOT86wE/tjr+I=
> 	dep	github.com/uw-labs/lichen	(devel)	
> ```
> 
> with Go 1.18.

Thanks, I can reproduce that now. So if seems that targetting `main.go` in particular yieds the issue, as `go build -o app .` results in the "normal" looking build info. I do wonder if that is an intended change Go side - either way, we'll have to address it. Thanks for raising a PR to fix, I'll take a look :+1:

**Comment by skitt** [comment]
> Thanks, I can reproduce that now. So if seems that targetting `main.go` in particular yieds the issue, as `go build -o app .` results in the "normal" looking build info. I do wonder if that is an intended change Go side - either way, we'll have to address it. Thanks for raising a PR to fix, I'll take a look +1

That’s right, and I’m updating the Submariner build to build packages instead of targetting `main.go` files ;-). As you say though, either way lichen needs to handle this.
